// A static, bundled list of known consulting firm names — powers FirmsEditor's Name field
// suggestions (components/ComboBox.tsx). Deliberately NOT persisted anywhere: typing a name
// that isn't on this list is fine (the combobox is still a plain free-text input under the
// hood) and applies only to the current project/session, exactly like any other firm name
// typed today — it's never written back to this list or saved outside the project itself.
// WFRC's own supplied starting list, not invented.

export const KNOWN_FIRMS: readonly string[] = [
  "3J",
  "AECOM",
  "Alpen Associates",
  "Alta Planning + Design",
  "Avenue Consultants",
  "BetterCity",
  "Bike Utah",
  "Cambridge Systematics",
  "Cascadia Partners",
  "CitiDesign",
  "Confluence",
  "Denton House",
  "Design Workshop",
  "DIGSTUDIO",
  "DKS",
  "DTRedevelopment",
  "ECOnorthwest",
  "Envision Utah",
  "Fehr & Peers",
  "FFKR Architects",
  "Felsburg Holt & Ullevig",
  "Galloway",
  "GC Garcia",
  "GSBS",
  "Hales Engineering",
  "Hansen Planning Group",
  "HDR",
  "High Street Consulting",
  "Horrocks",
  "Houseal Lavigne",
  "Insight Analytics + Urban Innovators",
  "io Landarch",
  "Jones & Associates",
  "Jones & DeMille Engineers",
  "JUB Engineers",
  "KGRW + BCT",
  "Kimley-Horn",
  "KW Commercial",
  "Landmark Design",
  "Laneshift",
  "Leland Consulting Group",
  "Logan Simpson",
  "LRB",
  "Methods Consulting",
  "MGB+A The Grassli Group",
  "MHTN",
  "MIG",
  "Mulled Pixel",
  "Nelson Nygaard",
  "Opticos Design",
  "Parametrix",
  "Perkins&Will",
  "Planning Outpost",
  "Psomas",
  "RCLCO",
  "RSG",
  "SE Group",
  "Sunrise Engineering",
  "Terracon",
  "Township & Range",
  "Transpo Group",
  "Urban Design Associates",
  "Urban3",
  "VCBO",
  "VODA",
  "Walker Consultants",
  "Wenk Associates",
  "Wilson & Company",
  "WSP",
  "ZGF",
  "Zions Public Finance",
];
