// T036: Parses one or more completed reviewer workbooks back into Score entries, per
// contracts/reviewer-workbook.md (FR-020, FR-021, FR-022). Reads hidden reviewerId/
// firmId/criterionId columns — never the visible Firm/Criterion text — since that's
// exactly what a reviewer could accidentally edit (FR-018).
//
// Header-row location, refined when generateWorkbook.ts moved to a single-sheet layout
// with a title/legend banner occupying the first few rows: this file does NOT hardcode
// "data starts at row 2" (or any other row number) — findHeaderRow scans for the literal
// "Firm" header text and derives the data start from wherever that actually is. This keeps
// generate/parse from needing to agree on a magic row number as a second, implicit
// contract on top of the documented one.
//
// Design note refining the original contract doc during implementation: the contract's
// round-trip test expects an unmodified (freshly generated, no scores filled in)
// workbook to parse with every row intact rather than flagged as a validation failure —
// but FR-021 also says a Score value failing validation must be excluded. Those two
// requirements only reconcile cleanly with a third row outcome: a genuinely BLANK Score
// cell is "not yet scored" (the same sparse-by-default philosophy the whole data model
// uses — data-model.md's Score section, spec FR-026), not a validation failure. So this
// implementation uses three statuses rather than the two originally sketched in the
// contract doc:
//   - "added"   — a valid, present Score value; will be committed.
//   - "skipped" — the row is structurally fine (IDs all resolve) but the Score cell is
//                 blank; nothing to commit, and NOT reported as an error.
//   - "failed"  — an out-of-scale Score value, or an ID that no longer resolves to a
//                 live entity in the current project; excluded, reported to the handler.
// contracts/reviewer-workbook.md is updated to match.

import ExcelJS from "exceljs";
import type { Project, Score } from "../../types/project";

export type RowStatus = "added" | "skipped" | "failed";

export interface ParsedRow {
  /** 1-indexed spreadsheet row number, for referring the handler back to it if needed. */
  row: number;
  status: RowStatus;
  /** Present for "failed" (why) and "skipped" (why nothing was added). */
  reason?: string;
  /** Present only for "added". */
  score?: Score;
}

export interface ParsedFileResult {
  filename: string;
  /** Best-effort — resolved from the first row whose reviewerId matches a live reviewer.
   * Undefined if no row in the file resolves to one (e.g. every row is corrupted). */
  reviewerName?: string;
  rows: ParsedRow[];
  addedCount: number;
  skippedCount: number;
  failedCount: number;
}

/** Reads a File's bytes as an ArrayBuffer via FileReader — not `File.arrayBuffer()` —
 * for the same reason uploadProject.ts's readFileText uses FileReader over `.text()`:
 * both are supported in every real target browser, but only FileReader also works in
 * jsdom's test environment. */
export async function readFileArrayBuffer(file: File): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as ArrayBuffer);
    reader.onerror = () => reject(reader.error ?? new Error("Failed to read file"));
    reader.readAsArrayBuffer(file);
  });
}

function parseScoreCellValue(raw: unknown): number | null {
  if (raw === null || raw === undefined || raw === "") return null;
  const num = typeof raw === "number" ? raw : Number(raw);
  return Number.isFinite(num) ? num : NaN; // NaN signals "present but not a number"
}

/** Scans the sheet's column A for the literal "Firm" header text (generateWorkbook.ts's
 * SCORING_HEADER_ROW content) and returns that row number, or null if not found within a
 * reasonable scan range. Bounded scan (not the full sheet) so a corrupted/unrelated file
 * with thousands of rows doesn't turn a "not our file" case into a slow scan. */
function findHeaderRow(sheet: ExcelJS.Worksheet): number | null {
  const maxScan = Math.min(sheet.rowCount, 20);
  for (let r = 1; r <= maxScan; r++) {
    if (sheet.getCell(`A${r}`).value === "Firm") return r;
  }
  return null;
}

/** Parses an already-loaded ExcelJS workbook (the "Scoring" sheet) against the *current*
 * project — not the project state at generation time, since configuration may have
 * changed since the form went out (contracts/reviewer-workbook.md). */
export function parseScoringWorkbook(
  project: Project,
  workbook: ExcelJS.Workbook,
  filename: string,
): ParsedFileResult {
  const sheet = workbook.getWorksheet("Scoring");
  if (!sheet) {
    return {
      filename,
      rows: [
        {
          row: 0,
          status: "failed",
          reason:
            'This file has no "Scoring" sheet — is it a reviewer workbook generated by this app?',
        },
      ],
      addedCount: 0,
      skippedCount: 0,
      failedCount: 1,
    };
  }

  const headerRow = findHeaderRow(sheet);
  if (headerRow === null) {
    return {
      filename,
      rows: [
        {
          row: 0,
          status: "failed",
          reason:
            'Could not find the header row on the "Scoring" sheet — is it a reviewer workbook generated by this app?',
        },
      ],
      addedCount: 0,
      skippedCount: 0,
      failedCount: 1,
    };
  }

  const scaleValues = new Set(project.scoringScale.map((p) => p.value));
  const rows: ParsedRow[] = [];
  let reviewerName: string | undefined;
  const now = new Date().toISOString();

  for (let r = headerRow + 1; r <= sheet.rowCount; r++) {
    const reviewerId = sheet.getCell(`F${r}`).value;
    const firmId = sheet.getCell(`G${r}`).value;
    const criterionId = sheet.getCell(`H${r}`).value;

    if (
      typeof reviewerId !== "string" ||
      typeof firmId !== "string" ||
      typeof criterionId !== "string"
    ) {
      rows.push({
        row: r,
        status: "failed",
        reason: "This row's hidden ID columns are missing or corrupted.",
      });
      continue;
    }

    const reviewer = project.reviewers.find((rv) => rv.id === reviewerId);
    const firm = project.firms.find((f) => f.id === firmId);
    const criterion = project.criteria.find((c) => c.id === criterionId);

    if (!reviewer) {
      rows.push({
        row: r,
        status: "failed",
        reason: "The reviewer for this row no longer exists in this project.",
      });
      continue;
    }
    reviewerName ??= reviewer.name;

    if (!firm) {
      rows.push({
        row: r,
        status: "failed",
        reason: "The firm for this row no longer exists in this project.",
      });
      continue;
    }
    if (!criterion) {
      rows.push({
        row: r,
        status: "failed",
        reason: "The criterion for this row no longer exists in this project.",
      });
      continue;
    }

    const rawScore = sheet.getCell(`D${r}`).value;
    const scoreValue = parseScoreCellValue(rawScore);

    if (scoreValue === null) {
      rows.push({ row: r, status: "skipped", reason: "No score entered yet." });
      continue;
    }
    if (Number.isNaN(scoreValue) || !scaleValues.has(scoreValue)) {
      rows.push({
        row: r,
        status: "failed",
        reason: `"${String(rawScore)}" is not one of this project's configured scale values.`,
      });
      continue;
    }

    const commentCell = sheet.getCell(`E${r}`).value;
    const comment = typeof commentCell === "string" ? commentCell : "";

    rows.push({
      row: r,
      status: "added",
      score: { reviewerId, firmId, criterionId, value: scoreValue, comment, updatedAt: now },
    });
  }

  return {
    filename,
    reviewerName,
    rows,
    addedCount: rows.filter((r) => r.status === "added").length,
    skippedCount: rows.filter((r) => r.status === "skipped").length,
    failedCount: rows.filter((r) => r.status === "failed").length,
  };
}

/** Full pipeline for one uploaded File: read bytes -> load workbook -> parse. */
export async function parseWorkbookFile(project: Project, file: File): Promise<ParsedFileResult> {
  const arrayBuffer = await readFileArrayBuffer(file);
  const workbook = new ExcelJS.Workbook();
  try {
    await workbook.xlsx.load(arrayBuffer);
  } catch {
    return {
      filename: file.name,
      rows: [
        { row: 0, status: "failed", reason: "This file could not be read as an Excel workbook." },
      ],
      addedCount: 0,
      skippedCount: 0,
      failedCount: 1,
    };
  }
  return parseScoringWorkbook(project, workbook, file.name);
}

/** Parses multiple uploaded files in one action (FR-020's multi-select). Each file is
 * parsed independently — one file's failure doesn't stop the others. */
export async function parseWorkbookFiles(
  project: Project,
  files: File[],
): Promise<ParsedFileResult[]> {
  return Promise.all(files.map((file) => parseWorkbookFile(project, file)));
}

/** Flattens every "added" row across a batch of parsed files into the Score[] ready to
 * upsert into project.scores (FR-023) — the commit step, called only after the handler
 * confirms the shown summary (FR-022). */
export function collectScoresToCommit(results: ParsedFileResult[]): Score[] {
  return results.flatMap((result) =>
    result.rows
      .filter((r): r is ParsedRow & { score: Score } => r.status === "added" && !!r.score)
      .map((r) => r.score),
  );
}
